fixed various side effect issues

diff --git a/blib b/blib
--- a/blib
+++ b/blib
@@ -68,11 +68,14 @@ BLIB_STORE=(
 	["BLIB_MODULE_LIST_CACHE"]=""
 	["BLIB_CB_REF_LIST_CACHE"]=""
 	["BLIB_ERR_HANDLER"]="b_defaultErrorHandler"
-	["BLIB_ERR_ESET"]=""
 	["BLIB_STANDALONE_MODE"]="1"
 	)
 #BLIB_ERR_*: used by B_E
 #BLIB_STANDALONE_MODE: set to 0 if this script is a standalone version generated by b_generateStandalone
+
+#exit code stored as part of [B_E](#B_E)
+#not part of the BLIB_STORE as it changes very frequently which makes measuring state changes to the BLIB_STORE for testing hard
+BLIB_ERR_ESET=""
 
 #last element = event handler in use before the last call to [b_setErrorHandler](#b_setErrorHandler)
 declare -ga BLIB_ERR_HANDLER_LAST=()
@@ -144,7 +147,7 @@ shopt -s expand_aliases
 #+The error handler can be re-defined at runtime with [b_setErrorHandler](#b_setErrorHandler).
 alias B_E='{
 #save exit code
-BLIB_STORE["BLIB_ERR_ESET"]=$?
+BLIB_ERR_ESET=$?
 
 #error?
 if [ -n "$B_ERR" ] ; then
@@ -165,7 +168,7 @@ if [ -n "$B_ERR" ] ; then
 fi
 
 #restore exit code (the && construct is required to bypass the shopt -e mode from erroring out in e.g. bats)
-blib_setExitCode "${BLIB_STORE["BLIB_ERR_ESET"]}" && blib_setExitCode "${BLIB_STORE["BLIB_ERR_ESET"]}"
+blib_setExitCode "$BLIB_ERR_ESET" && blib_setExitCode "$BLIB_ERR_ESET"
 }'
 #Note: {} groups must always end with a newline or ;
 
@@ -184,6 +187,7 @@ function b_printStackTrace {
 local skipLevel="${1:-1}"
 local pad=0
 
+local i=
 for (( i=$skipLevel; i < $(( ${#FUNCNAME[@]}-1 )); i++ )); do
 	local s=$(( $i+1 ))
 	local func="${FUNCNAME[$i]}"
@@ -624,14 +628,11 @@ exit 1
 #+@B_E
 function b_generateStandalone {
 local func="$1"
-local funcDec=""
 local dep=""
 local mod=""
 local modulePath=""
 local par=""
 shift
-
-funcDec="$(declare -f "$func")" || { B_ERR="Failed to find the declaration for the function $func."; B_E; }
 
 #parse params (printf '%q' escapes) & generate the function call
 local funcCall="$func"
@@ -645,6 +646,8 @@ done
 #parse blib, add the function call instead of blib_main or whatever else there is (we might be calling b_generateStandalone from standalone mode)
 local mainCnt=0
 local inMain=1
+local main=""
+local line=
 while IFS= read -r line ; do
 	if [ $inMain -eq 0 ] ; then
 		if [[ "$line" == "#BLIB_MAIN_END" ]] ; then
@@ -685,14 +688,13 @@ done
 
 #add function dependencies
 for dep in "$@" ; do
-	dec="$(declare -f "$dep")" || { B_ERR="Failed to find the declaration for the function $dep."; B_E; }
 	echo ""
-	echo "$dec"
+	declare -f "$dep" || { B_ERR="Failed to find the declaration for the function $dep."; B_E; }
 done
 
 #add function
 echo ""
-echo "$funcDec"
+declare -f "$func" || { B_ERR="Failed to find the declaration for the function $func."; B_E; }
 
 #add call to func
 echo ""
@@ -775,6 +777,7 @@ printf -v userEsc '%q' "$user"
 # - Linux won't allow us to change our own process permissions
 # - sudo is usually the better choice if available (as it is more likely to be able to run without password prompt)
 # - su should always be available (& is a blib dependency)
+local cmd=
 if command -v sudo &> /dev/null ; then
 	cmd="sudo -u ${userEsc} bash $eFileEsc"
 else
