introduced BLIB_STORE_VOLATILE

diff --git a/blib b/blib
--- a/blib
+++ b/blib
@@ -56,6 +56,8 @@
 #+### Global Variables ###
 
 #map to store global blib data (we use it to hide global variables from the namespace)
+#meant for data that may cause stateless testing with [runSL](#runSL) to fail (i.e. state changes here are monitored)
+#most module data should go here
 declare -gA BLIB_STORE
 BLIB_STORE=(
 	["BLIB_SCRIPT_DIR"]="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
@@ -65,17 +67,20 @@ BLIB_STORE=(
 	["BLIB_TESTS_DIR"]="${BLIB_STORE["BLIB_SCRIPT_DIR"]}/tests"
 	["BLIB_STATIC_DOC_DIR"]="${BLIB_STORE["BLIB_SCRIPT_DIR"]}/doc_static"
 	["BLIB_IMPORTED_MODULES"]=""
-	["BLIB_MODULE_LIST_CACHE"]=""
-	["BLIB_CB_REF_LIST_CACHE"]=""
 	["BLIB_ERR_HANDLER"]="b_defaultErrorHandler"
 	["BLIB_STANDALONE_MODE"]="1"
 	)
-#BLIB_ERR_*: used by B_E
 #BLIB_STANDALONE_MODE: set to 0 if this script is a standalone version generated by b_generateStandalone
 
-#exit code stored as part of [B_E](#B_E)
-#not part of the BLIB_STORE as it changes very frequently which makes measuring state changes to the BLIB_STORE for testing hard
-BLIB_ERR_ESET=""
+#another map to store global blib data
+#meant for data that changes quite frequently, but shouldn't cause stateless testing with [runSL](#runSL) to fail (i.e. state changes here are _not_ monitored)
+declare -gA BLIB_STORE_VOLATILE
+BLIB_STORE_VOLATILE=(
+	["BLIB_MODULE_LIST_CACHE"]=""
+	["BLIB_CB_REF_LIST_CACHE"]=""
+	["BLIB_ERR_ESET"]=""
+	)
+#BLIB_ERR_*: used by B_E
 
 #last element = event handler in use before the last call to [b_setErrorHandler](#b_setErrorHandler)
 declare -ga BLIB_ERR_HANDLER_LAST=()
@@ -147,7 +152,7 @@ shopt -s expand_aliases
 #+The error handler can be re-defined at runtime with [b_setErrorHandler](#b_setErrorHandler).
 alias B_E='{
 #save exit code
-BLIB_ERR_ESET=$?
+BLIB_STORE_VOLATILE["BLIB_ERR_ESET"]=$?
 
 #error?
 if [ -n "$B_ERR" ] ; then
@@ -168,7 +173,7 @@ if [ -n "$B_ERR" ] ; then
 fi
 
 #restore exit code (the && construct is required to bypass the shopt -e mode from erroring out in e.g. bats)
-blib_setExitCode "$BLIB_ERR_ESET" && blib_setExitCode "$BLIB_ERR_ESET"
+blib_setExitCode "${BLIB_STORE_VOLATILE["BLIB_ERR_ESET"]}" && blib_setExitCode "${BLIB_STORE_VOLATILE["BLIB_ERR_ESET"]}"
 }'
 #Note: {} groups must always end with a newline or ;
 
@@ -408,12 +413,12 @@ echo "$ret"
 #+returns: all available blib module names as newline-separated list
 function b_getBlibModules {
 #only compute if not in cache
-if [ -z "${BLIB_STORE["BLIB_MODULE_LIST_CACHE"]}" ] ; then
-	local ret="${BLIB_STORE["BLIB_SCRIPT_NAME"]}"
+if [ -z "${BLIB_STORE_VOLATILE["BLIB_MODULE_LIST_CACHE"]}" ] ; then
+	local ret="${BLIB_STORE_VOLATILE["BLIB_SCRIPT_NAME"]}"
 	ret="$ret"$'\n'"$(blib_getBlibModules "${BLIB_STORE["BLIB_LIB_DIR"]}")"
-	BLIB_STORE["BLIB_MODULE_LIST_CACHE"]="$(echo "$ret" | sort)"
+	BLIB_STORE_VOLATILE["BLIB_MODULE_LIST_CACHE"]="$(echo "$ret" | sort)"
 fi
-echo "${BLIB_STORE["BLIB_MODULE_LIST_CACHE"]}"
+echo "${BLIB_STORE_VOLATILE["BLIB_MODULE_LIST_CACHE"]}"
 }
 
 #blib_getModulePath [module]
@@ -868,12 +873,12 @@ echo ""
 echo "## Reference List ##    {#reflist}"
 echo ""
 
-BLIB_STORE["BLIB_CB_REF_LIST_CACHE"]="$(echo "${BLIB_STORE["BLIB_CB_REF_LIST_CACHE"]}" | sort)"
+BLIB_STORE_VOLATILE["BLIB_CB_REF_LIST_CACHE"]="$(echo "${BLIB_STORE_VOLATILE["BLIB_CB_REF_LIST_CACHE"]}" | sort)"
 
 local ref=""
 while IFS= read -r ref ; do
 	[ -n "$ref" ] && echo "[$ref](#$ref)"$'\n'
-done <<< "${BLIB_STORE["BLIB_CB_REF_LIST_CACHE"]}"
+done <<< "${BLIB_STORE_VOLATILE["BLIB_CB_REF_LIST_CACHE"]}"
 }
 
 #blib_docPostProcessingCallback [init target] [input] [file] [document output format]
@@ -921,7 +926,7 @@ if [ $initTarget -eq 0 ] ; then
 			line="$headerIndent $line $headerIndent    {#$name}"
 
 			#add to func list for further processing by doc end callback
-			BLIB_STORE["BLIB_CB_REF_LIST_CACHE"]="${BLIB_STORE["BLIB_CB_REF_LIST_CACHE"]}$name"$'\n'
+			BLIB_STORE_VOLATILE["BLIB_CB_REF_LIST_CACHE"]="${BLIB_STORE_VOLATILE["BLIB_CB_REF_LIST_CACHE"]}$name"$'\n'
 			#print full name
 			line="$line"$'\n'"<small>*${docId}/${name}*</small>"$'\n'
 
