B_E: use standard bash syntax
It's not really needed by bash as B_E is an alias that adds the
newline which bash needs. However it confuses shellcheck and
similar syntax checkers.

diff --git a/blib b/blib
--- a/blib
+++ b/blib
@@ -131,8 +131,8 @@ B_CONF_DIR="/etc/blib"
 #+```
 B_SCRIPT=""
 read -r -d '' B_SCRIPT << 'EOF'
-B_SCRIPT_DIR="$(readlink -f "${BASH_SOURCE[0]}")" || { B_ERR="Failed to compute B_SCRIPT_DIR." ; B_E }
-B_SCRIPT_DIR="$(dirname "$B_SCRIPT_DIR")" || { B_ERR="Failed to compute B_SCRIPT_DIR." ; B_E }
+B_SCRIPT_DIR="$(readlink -f "${BASH_SOURCE[0]}")" || { B_ERR="Failed to compute B_SCRIPT_DIR." ; B_E ; }
+B_SCRIPT_DIR="$(dirname "$B_SCRIPT_DIR")" || { B_ERR="Failed to compute B_SCRIPT_DIR." ; B_E ; }
 B_SCRIPT_NAME="${BASH_SOURCE[0]##*/}"
 EOF
 
@@ -167,11 +167,11 @@ shopt -s expand_aliases
 #+More examples:
 #+```bash
 #+#handle a potentially failing command:
-#+cmd || { B_ERR="cmd failed." ; B_E }
+#+cmd || { B_ERR="cmd failed." ; B_E ; }
 #+
 #+#capture stdout of a potentially failing command:
 #+local out=
-#+out="$(cmd)" || { B_ERR="cmd failed." ; B_E }
+#+out="$(cmd)" || { B_ERR="cmd failed." ; B_E ; }
 #+
 #+#handle multiple potentially failing commands in a try/catch like manner:
 #+(	set -e
@@ -595,7 +595,7 @@ local cmd=
 for ((i=0; i <= max; i++)) ; do
 	#use a temporary file as cache
 	#NOTE: this is the closest we can get to stdout/stderr as it is inherited/shared to subthreads similarly to stdout/stderr
-	cfile="$(mktemp)" || { B_ERR="Failed to allocate a temporary file." ; B_E }
+	cfile="$(mktemp)" || { B_ERR="Failed to allocate a temporary file." ; B_E ; }
 	BLIB_CACHING_MSG_HANDLER_CACHES["$i"]="$cfile"
 
 	if [ $B_TEST_MODE -ne 0 ] ; then
@@ -792,7 +792,7 @@ for dep in "$@" ; do
 	command -v "$dep" &> /dev/null || unmet="$dep"$'\n'"$unmet"
 done
 
-[ -z "$unmet" ] || { B_ERR="The script requires the following commands, but they were not found:"$'\n'"$unmet" ; B_E }
+[ -z "$unmet" ] || { B_ERR="The script requires the following commands, but they were not found:"$'\n'"$unmet" ; B_E ; }
 }
 
 #+b_import [module] [double import]
@@ -1110,7 +1110,7 @@ local outFormat="${1:-raw}"
 
 #create header
 local header=
-header="$(mktemp)" || { B_ERR="Failed to create a temp file." ; B_E }
+header="$(mktemp)" || { B_ERR="Failed to create a temp file." ; B_E ; }
 blib_getDocHeader "$outFormat" > "$header"
 
 input=( "$header"
@@ -1127,7 +1127,7 @@ fi
 echo -n "Generating the $outFormat documentation...  "
 "${BLIB_STORE["BLIB_CDOC"]}" --hl 2 --ex '^.*/tests/fixtures/.*$' \
 	--id '^.*/lib/(.*)$' --id '^.*/(blib)$' --id '^.*/(tests/.*)$' \
-	--verb "$header" -rid "$output" "${input[@]}" || { B_ERR="Failed to correctly execute ${BLIB_STORE["BLIB_CDOC"]}." ; B_E }
+	--verb "$header" -rid "$output" "${input[@]}" || { B_ERR="Failed to correctly execute ${BLIB_STORE["BLIB_CDOC"]}." ; B_E ; }
 
 rm -f "$header" &> /dev/null
 echo "Done."
@@ -1154,7 +1154,7 @@ if [ -z "$module" ] ; then
 		bats -p "$tst"
 		ret=$(( $ret + $?))
 		testFiles=$(( $testFiles +1 ))
-	done <<< "$(set -o pipefail ; find "$testDir" -name "*.bats" | sort)" || { B_ERR="Failed to execute find." ; B_E }
+	done <<< "$(set -o pipefail ; find "$testDir" -name "*.bats" | sort)" || { B_ERR="Failed to execute find." ; B_E ; }
 
 	[ $testFiles -le 2 ] && B_ERR="Failed to find any relevant tests." && B_E
 
@@ -1174,7 +1174,7 @@ local modulePath=""
 
 modulePath="$(blib_getModulePath "$module")" || { B_ERR="Invalid or non-existing module: $module"; B_E; }
 
-"${BLIB_STORE["BLIB_CDOC"]}" --id '^.*/lib/(.*)$' --id '^.*/(blib)$' -id ".raw" "$modulePath" || { B_ERR="Failed to correctly execute ${BLIB_STORE["BLIB_CDOC"]}." ; B_E }
+"${BLIB_STORE["BLIB_CDOC"]}" --id '^.*/lib/(.*)$' --id '^.*/(blib)$' -id ".raw" "$modulePath" || { B_ERR="Failed to correctly execute ${BLIB_STORE["BLIB_CDOC"]}." ; B_E ; }
 
 return 0
 }
diff --git a/lib/cdoc b/lib/cdoc
--- a/lib/cdoc
+++ b/lib/cdoc
@@ -209,10 +209,10 @@ local rawOut="$(mktemp)"
 local blockOut="$(mktemp)"
 
 #generate the final file list
-fileList="$(b_fs_enumerate "$fileList")" || { B_ERR="Failed to enumerate the file list." ; B_E }
+fileList="$(b_fs_enumerate "$fileList")" || { B_ERR="Failed to enumerate the file list." ; B_E ; }
 
 #call doc begin callback
-${BLIB_STORE["BLIB_CDOC_DOCUMENT_BEGIN_CALLBACK"]} "$outFile" "$outFormat" >> "$rawOut" || { B_ERR="The document begin callback function ${BLIB_STORE["BLIB_CDOC_DOCUMENT_BEGIN_CALLBACK"]} returned an error." ; B_E }
+${BLIB_STORE["BLIB_CDOC_DOCUMENT_BEGIN_CALLBACK"]} "$outFile" "$outFormat" >> "$rawOut" || { B_ERR="The document begin callback function ${BLIB_STORE["BLIB_CDOC_DOCUMENT_BEGIN_CALLBACK"]} returned an error." ; B_E ; }
 
 #extract the documentation from the code / generate the raw doc
 local fname=""
@@ -238,9 +238,9 @@ while IFS= read -r fname ; do
 				if [ -n "$block" ] ; then
 					#call block callback
 					#NOTE: we do this in the current shell to support usage of global variables within the callback
-					${BLIB_STORE["BLIB_CDOC_BLOCK_CALLBACK"]} "$block" $blockCnt "$fname" "$outFormat" > "$blockOut" || { B_ERR="The block callback function ${BLIB_STORE["BLIB_CDOC_BLOCK_CALLBACK"]} returned an error." ; B_E }
+					${BLIB_STORE["BLIB_CDOC_BLOCK_CALLBACK"]} "$block" $blockCnt "$fname" "$outFormat" > "$blockOut" || { B_ERR="The block callback function ${BLIB_STORE["BLIB_CDOC_BLOCK_CALLBACK"]} returned an error." ; B_E ; }
 					#NOTE: the x stuff is just done in order to keep trailing newlines
-					block="$(cat "$blockOut" ; echo x)" || { B_ERR="Failed to read from the block output for the file $fname." ; B_E }
+					block="$(cat "$blockOut" ; echo x)" || { B_ERR="Failed to read from the block output for the file $fname." ; B_E ; }
 					block="${block%x}"
 					[ -n "$o" ] && o="${o}$block" || o="$block"
 					block=""
@@ -248,12 +248,12 @@ while IFS= read -r fname ; do
 				fi
 				lastMatched=1
 			fi
-		done < "$fname" || { B_ERR="Failed to read the code file $fname." ; B_E }
+		done < "$fname" || { B_ERR="Failed to read the code file $fname." ; B_E ; }
 		;;
 
 		"1")
 		#include as-is
-		o="$(cat "$fname" ; echo x)" || { B_ERR="Failed to read ${fname}." ; B_E }
+		o="$(cat "$fname" ; echo x)" || { B_ERR="Failed to read ${fname}." ; B_E ; }
 		o="${o%x}"
 		;;
 
@@ -269,14 +269,14 @@ while IFS= read -r fname ; do
 	esac
 
 	#call post processing callback
-	${BLIB_STORE["BLIB_CDOC_POST_PROCESSING_CALLBACK"]} "$o" "$fname" "$outFormat" >> "$rawOut" || { B_ERR="The post processing callback function ${BLIB_STORE["BLIB_CDOC_POST_PROCESSING_CALLBACK"]} returned an error." ; B_E }
+	${BLIB_STORE["BLIB_CDOC_POST_PROCESSING_CALLBACK"]} "$o" "$fname" "$outFormat" >> "$rawOut" || { B_ERR="The post processing callback function ${BLIB_STORE["BLIB_CDOC_POST_PROCESSING_CALLBACK"]} returned an error." ; B_E ; }
 done <<< "$fileList"
 
 #cleanup
 rm -f "$blockOut"
 
 #call doc end callback
-${BLIB_STORE["BLIB_CDOC_DOCUMENT_END_CALLBACK"]} "$outFile" "$outFormat" >> "$rawOut" || { B_ERR="The document end callback function ${BLIB_STORE["BLIB_CDOC_DOCUMENT_END_CALLBACK"]} returned an error." ; B_E }
+${BLIB_STORE["BLIB_CDOC_DOCUMENT_END_CALLBACK"]} "$outFile" "$outFormat" >> "$rawOut" || { B_ERR="The document end callback function ${BLIB_STORE["BLIB_CDOC_DOCUMENT_END_CALLBACK"]} returned an error." ; B_E ; }
 
 #convert to output format if needed
 if [ -n "$outFormat" ] ; then
@@ -284,13 +284,13 @@ if [ -n "$outFormat" ] ; then
 	[[ "$outFormat" != "pandoc" ]] && formatParam="-t $outFormat"
 	
 	#call pandoc
-	pandoc "${@:4}" $internalAddOptions $formatParam -o "$outFile" "$rawOut" || { B_ERR="Errors detected during the pandoc conversion. Please review the pandoc output for details." ; B_E }
+	pandoc "${@:4}" $internalAddOptions $formatParam -o "$outFile" "$rawOut" || { B_ERR="Errors detected during the pandoc conversion. Please review the pandoc output for details." ; B_E ; }
 
 	#cleanup
 	rm -f "$rawOut"
 else
 	#no conversion required --> move raw file to output
-	mv -f "$rawOut" "$outFile" || { B_ERR="Failed to move the raw output in $rawOut to $outFile." ; B_E }
+	mv -f "$rawOut" "$outFile" || { B_ERR="Failed to move the raw output in $rawOut to $outFile." ; B_E ; }
 fi
 
 return 0
@@ -319,7 +319,7 @@ case "$outFormat" in
 	;;
 
 	pdf)
-	[[ "$cdocOutput" == *".pdf" ]] || { B_ERR="Currently only output files of format pdf with a pdf file ending are supported. So please adjust your file name." ; B_E }
+	[[ "$cdocOutput" == *".pdf" ]] || { B_ERR="Currently only output files of format pdf with a pdf file ending are supported. So please adjust your file name." ; B_E ; }
 	cdocOutFormat="pandoc"
 	;;
 
@@ -344,7 +344,7 @@ esac
 
 #generate the doc
 local out=""
-out="$(b_cdoc_generate "$fileList" "$cdocOutput" "$cdocOutFormat" "${cdocAdditional[@]}")" || { B_ERR="Failed to generate the doc: $out" ; B_E }
+out="$(b_cdoc_generate "$fileList" "$cdocOutput" "$cdocOutFormat" "${cdocAdditional[@]}")" || { B_ERR="Failed to generate the doc: $out" ; B_E ; }
 
 #return
 echo "$cdocOutput"
diff --git a/lib/flog b/lib/flog
--- a/lib/flog
+++ b/lib/flog
@@ -140,22 +140,22 @@ BLIB_STORE["BLIB_FLOG_INTERMEDIATE"]="${5:-$(b_getDefaultMessageHandlerIntermedi
 
 #generate ID (exactly one ID per output must be generated)
 local path="$(readlink -m "${BLIB_STORE["BLIB_FLOG_FILENAME"]}")"
-BLIB_STORE["BLIB_FLOG_ID"]="$(b_hash_str "$path")" || { B_ERR="Failed to obtain the md5 sum for $path." ; B_E }
+BLIB_STORE["BLIB_FLOG_ID"]="$(b_hash_str "$path")" || { B_ERR="Failed to obtain the md5 sum for $path." ; B_E ; }
 
 #create the mutex directory, if needed
 if [ ${BLIB_STORE["BLIB_FLOG_THREAD_SAFE"]} -eq 0 ] ; then
-	mkdir -p "${BLIB_STORE["BLIB_FLOG_MTX_DIR"]}" || { B_ERR="Failed to create ${BLIBBLIB_STORE["BLIB_FLOG_MTX_DIR"]}." ; B_E }
+	mkdir -p "${BLIB_STORE["BLIB_FLOG_MTX_DIR"]}" || { B_ERR="Failed to create ${BLIBBLIB_STORE["BLIB_FLOG_MTX_DIR"]}." ; B_E ; }
 fi
 
 #create the output file, if needed
 if [[ "${BLIB_STORE["BLIB_FLOG_FILENAME"]}" != "/dev/"* ]] ; then
 	[[ "${BLIB_STORE["BLIB_FLOG_FILENAME"]}" != *"/"* ]] && B_ERR="Unexpected file name without slashes: ${BLIB_STORE["BLIB_FLOG_FILENAME"]}" && B_E
-	mkdir -p "${BLIB_STORE["BLIB_FLOG_FILENAME"]%/*}" || { B_ERR="Failed to create the parent directories of ${BLIB_STORE["BLIB_FLOG_FILENAME"]}." ; B_E }
+	mkdir -p "${BLIB_STORE["BLIB_FLOG_FILENAME"]%/*}" || { B_ERR="Failed to create the parent directories of ${BLIB_STORE["BLIB_FLOG_FILENAME"]}." ; B_E ; }
 	[ ! -e "${BLIB_STORE["BLIB_FLOG_FILENAME"]}" ] && > "${BLIB_STORE["BLIB_FLOG_FILENAME"]}"
 fi
 
 #open the output for appending, let bash choose the file descriptor
-exec {BLIB_STORE["BLIB_FLOG_FD"]}>>"${BLIB_STORE["BLIB_FLOG_FILENAME"]}" || { B_ERR="Failed to open the log output ${BLIB_STORE["BLIB_FLOG_FILENAME"]}." ; B_E }
+exec {BLIB_STORE["BLIB_FLOG_FD"]}>>"${BLIB_STORE["BLIB_FLOG_FILENAME"]}" || { B_ERR="Failed to open the log output ${BLIB_STORE["BLIB_FLOG_FILENAME"]}." ; B_E ; }
 
 #set the init done flag
 BLIB_STORE["BLIB_FLOG_INIT_DONE"]=0
@@ -182,14 +182,14 @@ if  [[ "${BLIB_STORE["BLIB_FLOG_FILENAME"]}" != "/dev/"* ]] && [ ${BLIB_STORE["B
 		[ ! -f "$log" ] && return 0
 
 		#count lines
-		cnt="$(b_fs_getLineCount "$log")" || { B_ERR="Failed to count the number of lines of ${log}." ; B_E }
+		cnt="$(b_fs_getLineCount "$log")" || { B_ERR="Failed to count the number of lines of ${log}." ; B_E ; }
 		
 		#reduce if necessary
 		if [ $cnt -gt ${BLIB_STORE["BLIB_FLOG_LOG_LINES_UB"]} ] ; then
 			local tmp=""
-			tmp="$(mktemp)" || { B_ERR="Failed to create a temp file." ; B_E }
-			tail -n ${BLIB_STORE["BLIB_FLOG_LOG_LINES_LB"]} "$log" > "$tmp" || { B_ERR="Failed to reduce the log $log." ; B_E }
-			cat "$tmp" > "$log" || { B_ERR="Failed to write the reduced log back." ; B_E }
+			tmp="$(mktemp)" || { B_ERR="Failed to create a temp file." ; B_E ; }
+			tail -n ${BLIB_STORE["BLIB_FLOG_LOG_LINES_LB"]} "$log" > "$tmp" || { B_ERR="Failed to reduce the log $log." ; B_E ; }
+			cat "$tmp" > "$log" || { B_ERR="Failed to write the reduced log back." ; B_E ; }
 			rm -f "$tmp" &> /dev/null
 			b_flog_log "Reduced the log to its last ${BLIB_STORE["BLIB_FLOG_LOG_LINES_LB"]} lines." || B_E
 		fi
@@ -242,7 +242,7 @@ fi
 #obtain mutex, if necessary
 local mtx="${BLIB_STORE["BLIB_FLOG_MTX_DIR"]}/${BLIB_STORE["BLIB_FLOG_ID"]}"
 if [ ${BLIB_STORE["BLIB_FLOG_THREAD_SAFE"]} -eq 0 ] ; then
-	b_mtx_waitFor "$mtx" "$BASHPID" 0 -1 > /dev/null || { B_ERR="Failed to obtain the log file mutex." ; B_E }
+	b_mtx_waitFor "$mtx" "$BASHPID" 0 -1 > /dev/null || { B_ERR="Failed to obtain the log file mutex." ; B_E ; }
 fi
 
 #write
diff --git a/lib/fs b/lib/fs
--- a/lib/fs
+++ b/lib/fs
@@ -33,8 +33,8 @@ local file="$1"
 local cnt=""
 
 #NOTE: unfortunately wc -l includes the file name
-cnt="$(wc -l "$file")" || { B_ERR="Failed to read the file $file." ; B_E }
-[[ "$cnt" =~ ^([0-9]+) ]] && cnt="${BASH_REMATCH[1]}" || { B_ERR="Failed to obtain the line count for the file $file." ; B_E }
+cnt="$(wc -l "$file")" || { B_ERR="Failed to read the file $file." ; B_E ; }
+[[ "$cnt" =~ ^([0-9]+) ]] && cnt="${BASH_REMATCH[1]}" || { B_ERR="Failed to obtain the line count for the file $file." ; B_E ; }
 
 echo "$cnt"
 }
@@ -92,7 +92,7 @@ local ret=
 ret="$(b_fs_getMountpoints "$dev")"
 
 if [ -n "$mp" ] ; then
-	mkdir -p "$mp" || { B_ERR="Failed to create the parent directories of $mp." ; B_E }
+	mkdir -p "$mp" || { B_ERR="Failed to create the parent directories of $mp." ; B_E ; }
 
 	if [ $enforce -eq 0 ] ; then
 		#NOTE: we use findmnt as devices and mount points can come in many notations
@@ -100,7 +100,7 @@ if [ -n "$mp" ] ; then
 			local cur=
 			while IFS= read -r cur ; do
 				if [ -n "$cur" ] ; then
-					mount --bind "$cur" "$mp" &> /dev/null || { B_ERR="Failed to rebind $cur to $mp." ; B_E }
+					mount --bind "$cur" "$mp" &> /dev/null || { B_ERR="Failed to rebind $cur to $mp." ; B_E ; }
 					ret="$mp"$'\n'"$ret"
 					break
 				fi
@@ -115,10 +115,10 @@ if [ -n "$ret" ] ; then
 fi
 
 if [ -z "$mp" ] ; then
-	mp="$(mktemp -d)" || { B_ERR="Failed to create a temporary directory." ; B_E }
+	mp="$(mktemp -d)" || { B_ERR="Failed to create a temporary directory." ; B_E ; }
 fi
 
-mount $mopts "$dev" "$mp" &> /dev/null && echo "$mp" || { B_ERR="Failed to mount the device $dev to $mp." ; B_E }
+mount $mopts "$dev" "$mp" &> /dev/null && echo "$mp" || { B_ERR="Failed to mount the device $dev to $mp." ; B_E ; }
 }
 
 #+b_fs_createLoopDeviceIfNecessary [file]
@@ -145,7 +145,7 @@ if [ $? -ne 0 ] ; then
 		#no old device --> create a new one
 		#we use the exit code as ours
 		#usually requires root access rights
-		losetup -f --show "$file" || { B_ERR="Failed to create a loop device from $file." ; B_E }
+		losetup -f --show "$file" || { B_ERR="Failed to create a loop device from $file." ; B_E ; }
 	fi
 fi
 }
@@ -161,25 +161,25 @@ local loop=
 local file=
 if [ -b "$in" ] ; then
 	loop="$in"
-	file="$(losetup -n --raw -O "back-file" "$loop")" || { B_ERR="Failed to execute losetup -n." ; B_E }
+	file="$(losetup -n --raw -O "back-file" "$loop")" || { B_ERR="Failed to execute losetup -n." ; B_E ; }
 	#NOTE: the kernel often leaves the node alone after losetup -d was called on an existing loop device --> -b may return true, even if the loop device is down; the back-file check will return no file, but a zero exit code then
 	[ -z "$file" ] && return 0
 elif [ -f "$in" ] ; then
 	#NOTE: losetup returns a zero exit code below even if the file does not exist _or_ has no loop device
-	loop="$(losetup -j "$in" -O "name" --raw -n)" || { B_ERR="Failed to execute losetup -j." ; B_E }
+	loop="$(losetup -j "$in" -O "name" --raw -n)" || { B_ERR="Failed to execute losetup -j." ; B_E ; }
 	file="$in"
 	[ -z "$loop" ] && return 0
 	local loopCnt="$(echo "$loop" | wc -l)"
-	[ $loopCnt -ne 1 ] && { B_ERR="$loopCnt loop devices detected for $in. Backing off..." ; B_E }
+	[ $loopCnt -ne 1 ] && { B_ERR="$loopCnt loop devices detected for $in. Backing off..." ; B_E ; }
 else
 	return 0
 fi
 
 #NOTE: losetup -d only _asks_ the kernel to remove the loop, if it's unused --> we need to give the kernel some time & check whether it was removed
-losetup -d "$loop" || { B_ERR="Failed to execute losetup -d." ; B_E }
+losetup -d "$loop" || { B_ERR="Failed to execute losetup -d." ; B_E ; }
 sleep 0.1
 local out=
-out="$(losetup -j "$file" -O "name" --raw -n)" || { B_ERR="Failed to execute losetup." ; B_E }
+out="$(losetup -j "$file" -O "name" --raw -n)" || { B_ERR="Failed to execute losetup." ; B_E ; }
 #NOTE:
 # - losetup returns a zero exit code even if there's no matching file
 # - if the loop was recreated by another process in the meantime, the file is hopefully a different one
@@ -198,7 +198,7 @@ local str="$1"
 local checkFlag="${2:-0}"
 
 local re='^[[:space:]]*([\+\-]?)([0-9]+)([bBkKmMgGtTpP]?[bB]?)[[:space:]]*$'
-[[ "$str" =~ $re ]] || { B_ERR="Failed to parse the size: $str" ; B_E }
+[[ "$str" =~ $re ]] || { B_ERR="Failed to parse the size: $str" ; B_E ; }
 
 local pref="${BASH_REMATCH[1]}"
 local num="${BASH_REMATCH[2]}"
@@ -245,15 +245,15 @@ function b_fs_removeWithOverwrite {
 local file="$1"
 local rdev="${2:-/dev/urandom}"
 
-[ -f "$file" ] || { B_ERR="The file $file doesn't exist." ; B_E }
-[ -c "$rdev" ] || { B_ERR="Nonexisting randomness source: $rdev" ; B_E }
+[ -f "$file" ] || { B_ERR="The file $file doesn't exist." ; B_E ; }
+[ -c "$rdev" ] || { B_ERR="Nonexisting randomness source: $rdev" ; B_E ; }
 
 local fsize=
-fsize="$(stat -c '%s' "$file")" || { B_ERR="Failed to identify the size of the file $file." ; B_E }
+fsize="$(stat -c '%s' "$file")" || { B_ERR="Failed to identify the size of the file $file." ; B_E ; }
 
-head -c "$fsize" < "$rdev" > "$file" || { B_ERR="Failed to overwrite the file $file." ; B_E }
-sync -d "$file" || { B_ERR="Failed to sync the file $file." ; B_E }
-rm -f "$file" || { B_ERR="Failed to remove the file $file." ; B_E }
+head -c "$fsize" < "$rdev" > "$file" || { B_ERR="Failed to overwrite the file $file." ; B_E ; }
+sync -d "$file" || { B_ERR="Failed to sync the file $file." ; B_E ; }
+rm -f "$file" || { B_ERR="Failed to remove the file $file." ; B_E ; }
 return 0
 }
 
@@ -299,6 +299,6 @@ function b_fs_enumerate {
 	#subshell just for temporary shell options
 	shopt -s dotglob
 	blib_fs_enumerate "$@"
-	) || { B_ERR="Failed to enumerate the given paths." ; B_E }
+	) || { B_ERR="Failed to enumerate the given paths." ; B_E ; }
 return 0
 }
diff --git a/lib/multithreading/ipcv b/lib/multithreading/ipcv
--- a/lib/multithreading/ipcv
+++ b/lib/multithreading/ipcv
@@ -29,8 +29,8 @@ BLIB_STORE["BLIB_IPCV_TEMP_NAME"]="temp"
 BLIB_STORE["BLIB_IPCV_TEMP"]="${BLIB_STORE["BLIB_IPCV_SHM_BASE"]}/${BLIB_STORE["BLIB_IPCV_TEMP_NAME"]}"
 
 #safety check & some init
-findmnt "/dev/shm" &> /dev/null || { B_ERR="Your system does not appear to use /dev/shm. Thus you cannot use the ipcv module." ; B_E }
-mkdir -p "${BLIB_STORE["BLIB_IPCV_TEMP"]}" || { B_ERR="Failed to create the directory $BLIB_IPCV_TEMP." ; B_E }
+findmnt "/dev/shm" &> /dev/null || { B_ERR="Your system does not appear to use /dev/shm. Thus you cannot use the ipcv module." ; B_E ; }
+mkdir -p "${BLIB_STORE["BLIB_IPCV_TEMP"]}" || { B_ERR="Failed to create the directory $BLIB_IPCV_TEMP." ; B_E ; }
 
 #+### Functions ###
 
@@ -69,21 +69,21 @@ blib_ipcv_assertCorrectNamespace "$ns" || B_E
 shift
 
 local nsDir="${BLIB_STORE["BLIB_IPCV_SHM_BASE"]}/$ns"
-mkdir -p "$nsDir" || { B_ERR="Failed to create the directory for the namespace at $nsDir." ; B_E }
+mkdir -p "$nsDir" || { B_ERR="Failed to create the directory for the namespace at $nsDir." ; B_E ; }
 
 local ret=0
 local tmp=
 local out=
 local var=
 for var in "$@" ; do
-	tmp="$(mktemp -p "${BLIB_STORE["BLIB_IPCV_TEMP"]}")" || { B_ERR="Failed to create a temporary memory object." ; B_E }
-	out="$(declare -p "$var")" || { rm -f "$tmp" &> /dev/null ; B_ERR="Failed to find the variable ${var}." ; B_E }
+	tmp="$(mktemp -p "${BLIB_STORE["BLIB_IPCV_TEMP"]}")" || { B_ERR="Failed to create a temporary memory object." ; B_E ; }
+	out="$(declare -p "$var")" || { rm -f "$tmp" &> /dev/null ; B_ERR="Failed to find the variable ${var}." ; B_E ; }
 
 	#NOTE: unfortunately declare -p doesn't save the very important -g in some bash versions --> we need to add it
-	echo "${out/declare/declare -g}" > "$tmp" || { rm -f "$tmp" &> /dev/null ; B_ERR="Failed to write the variable ${var}." ; B_E }
+	echo "${out/declare/declare -g}" > "$tmp" || { rm -f "$tmp" &> /dev/null ; B_ERR="Failed to write the variable ${var}." ; B_E ; }
 
 	#NOTE: the below mv should be atomic on almost all Linux distros
-	mv -f "$tmp" "$nsDir/$var" || { rm -f "$tmp" &> /dev/null ; B_ERR="Failed to move a temporary memory object for the variable $var." ; B_E }
+	mv -f "$tmp" "$nsDir/$var" || { rm -f "$tmp" &> /dev/null ; B_ERR="Failed to move a temporary memory object for the variable $var." ; B_E ; }
 done
 
 return 0
@@ -146,7 +146,7 @@ for varPath in "$nsDir"/* "$nsDir"/.[^.]* ; do
 	vars+=( "$var" )
 done
 
-blib_ipcv_load "$ns" "${vars[@]}" || { B_ERR="Failed to load the namespace $ns." ; B_E }
+blib_ipcv_load "$ns" "${vars[@]}" || { B_ERR="Failed to load the namespace $ns." ; B_E ; }
 return 0
 }
 
@@ -185,7 +185,7 @@ blib_ipcv_assertCorrectNamespace "$ns" || B_E
 
 local nsDir="${BLIB_STORE["BLIB_IPCV_SHM_BASE"]}/$ns"
 if [ -d "$nsDir" ] ; then
-	rm -rf "$nsDir" || { B_ERR="Failed to unset the namespace ${ns}." ; B_E }
+	rm -rf "$nsDir" || { B_ERR="Failed to unset the namespace ${ns}." ; B_E ; }
 else
 	[ -e "$nsDir" ] && B_ERR="Invalid namespace $ns provided ($nsDir appears to be no directory)." && B_E
 fi
diff --git a/lib/multithreading/mtx b/lib/multithreading/mtx
--- a/lib/multithreading/mtx
+++ b/lib/multithreading/mtx
@@ -44,9 +44,9 @@ local baseDir="$1"
 
 #use mktemp & its return value
 if [ -n "$baseDir" ] ; then
-	mktemp -p "$baseDir" -d -u || { B_ERR="Failed to create a temp dir." ; B_E }
+	mktemp -p "$baseDir" -d -u || { B_ERR="Failed to create a temp dir." ; B_E ; }
 else
-	mktemp -d -u || { B_ERR="Failed to create a temp dir." ; B_E }
+	mktemp -d -u || { B_ERR="Failed to create a temp dir." ; B_E ; }
 fi
 }
 
@@ -119,10 +119,10 @@ local mutex="$1"
 local blockId="$2"
 local blockFile="$mutex/$blockId"
 local oldBlockId=
-oldBlockId="$(blib_mtx_getBlockIdFor "$mutex")" || { B_ERR="The mutex $mutex does not exist or we had issues identifying it." ; B_E }
+oldBlockId="$(blib_mtx_getBlockIdFor "$mutex")" || { B_ERR="The mutex $mutex does not exist or we had issues identifying it." ; B_E ; }
 local oldBlockFile="$mutex/$oldBlockId"
 
-touch "$blockFile" &> /dev/null || { B_ERR="Failed to write to $blockFile. Maybe the mutex $mutex was released in the meantime?" ; B_E }
+touch "$blockFile" &> /dev/null || { B_ERR="Failed to write to $blockFile. Maybe the mutex $mutex was released in the meantime?" ; B_E ; }
 if ! rm -f "$oldBlockFile" &> /dev/null ; then
 	rm -f "$blockFile" &> /dev/null
 	B_ERR="Failed to remove the old block ID $oldBlockFile."
@@ -144,9 +144,9 @@ return 0
 #+```bash
 #+ local mutex=""
 #+ local mutexRet=""
-#+ mutex="$(b_mtx_create)" || { B_ERR="Failed to create a mutex." ; B_E }
+#+ mutex="$(b_mtx_create)" || { B_ERR="Failed to create a mutex." ; B_E ; }
 #+ mutexRet="$(b_mtx_try "$mutex")" \
-#+ || { B_ERR="Failed to obtain the mutex $mutex. Reason: $mutexRet" ; B_E }
+#+ || { B_ERR="Failed to obtain the mutex $mutex. Reason: $mutexRet" ; B_E ; }
 #+ #assuming the mutex is only meant to be removed after full
 #+ #execution of the script:
 #+ trap "$mutexRet" EXIT
