added b_dom0_getQvmBlockInfo

diff --git a/lib/os/qubes4/dom0 b/lib/os/qubes4/dom0
--- a/lib/os/qubes4/dom0
+++ b/lib/os/qubes4/dom0
@@ -631,7 +631,7 @@ b_silence b_dom0_qvmRun "$vm" "$cmd" || { B_ERR="Failed to run cryptsetup close 
 #+Parse data from `qvm-block ls` to an associative array.
 #+The indices of the associative array will be of the format _\[counter\]\_\[field\]_ (counters run from 0 (inclusive) to max (exclusive)).
 #+The special index "max" is equal to the number of lines. It can be used for iterations over the map.
-#+Currently supported \[field\] values: backend|device id|description|used by|read-only|frontend-dev
+#+Currently supported \[field\] values: backend|device id|id|description|used by|read-only|frontend-dev
 #+[variable name]: Name of the associative array to use as output.
 #+[input]: Optional output from a previous `qvm-block ls` call; if none is specified, this function will execute the call and use its output.
 #+returns: A string specifying an associative array in bash syntax. You can eval that string to obtain all relevant data. On errors [B_E](#B_E) is called.
@@ -661,11 +661,12 @@ while IFS= read -r line ; do
 	#skip header
 	[[ "$line" == "BACKEND:DEVID"* ]] && continue
 
-	#parse backend & device id
+	#parse backend & device id & id
 	local regex='^([^[:blank:]:]+):([^[:blank:]]+)[[:blank:]]{2,}(.*)$'
 	if [[ "$line" =~ $regex ]] ; then
 		ret["${i}_backend"]="${BASH_REMATCH[1]}"
 		ret["${i}_device id"]="${BASH_REMATCH[2]}"
+		ret["${i}_id"]="${BASH_REMATCH[1]}:${BASH_REMATCH[2]}"
 
 		#parse description
 		local rem="${BASH_REMATCH[3]}"
@@ -725,6 +726,62 @@ ret="$(declare -p ret 2> /dev/null)" || { B_ERR="Failed to parse the qvm-block l
 echo "${ret/declare -A ret/declare -A $outVar}"
 }
 
+#+b_dom0_getQvmBlockInfo [input] [retrieve field] [filter field 1] [filter value 1] .. [filter field n] .. [filter value n]
+#+Convenience function to retrieve information from `qvm-block ls`.
+#+Searches for the given filter values in the given fields and retrieves the first field value matching all filters.
+#+More simple, but less flexible than [b_dom0_parseQvmBlock](#b_dom0_parseQvmBlock).
+#+[input]: Optional output from a previous `qvm-block ls` call; if none is specified, this function will execute the call and use its output.
+#+[retrieve field]: Name of the field to retrieve.
+#+[filter field i]: Name of any field supported by [b_dom0_parseQvmBlock](#b_dom0_parseQvmBlock).
+#+[filter value i]: The value to search for in \[filter field i\] (equality check).
+#+returns: The value of the requested field and sets a zero exit code on success. Sets a non-zero exit code if no matching value could be found. On errors [B_E](#B_E) is called.
+#+@B_E
+function b_dom0_getQvmBlockInfo {
+local input="$1"
+shift
+local retField="$1"
+shift
+
+local blockinfo=""
+blockinfo="$(b_dom0_parseQvmBlock "blockinfo" "$input")" || { B_ERR="Failed to obtain the qvm-block ls information." ; B_E }
+eval "$blockinfo" || { B_ERR="b_dom0_parseQvmBlock output incorrect." ; B_E }
+local i=0
+local checkField=""
+local checkValue=""
+local matching=
+for ((i=0; i < ${blockinfo["max"]}; i++)) ; do
+	local j=0
+	matching=0
+
+	#check for non-matching entry
+	for ((j=1; j <= $# ; j++)) ; do
+		if [ $(( $j % 2 )) -eq 1 ] ; then
+			checkField="${!j}"
+		else
+			checkValue="${!j}"
+
+			if [[ "${blockinfo["${i}_$checkField"]}" != "$checkValue" ]] ; then
+				matching=1
+				break
+			fi
+		fi
+	done
+
+	#return matching entry
+	if [ $matching -eq 0 ] ; then
+		if [ "${blockinfo["${i}_$retField"]+exists}" ] ; then
+			echo "${blockinfo["${i}_$retField"]}"
+			return 0
+		else
+			B_ERR="Requested a non-existing field $retField."
+			B_E
+		fi
+	fi
+done
+
+return 1
+}
+
 #+b_dom0_attachFile [dom0 file] [target VM] [rw flag]
 #+Attach the given file from dom0 (!) as block device to the target VM.
 #+
@@ -754,23 +811,10 @@ loDeviceName="${loDevice##*/}"
 qvm-block a $addOptions "$targetVM" "dom0:${loDeviceName}" || { B_ERR="Failed to attach the loop device $loDeviceName to the VM $targetVM." ; B_E }
 
 #retrieve info
-local blockinfo=""
-blockinfo="$(b_dom0_parseQvmBlock "blockinfo")" || { B_ERR="Failed to obtain the qvm-block ls information." ; B_E }
-eval "$blockinfo" || { B_ERR="b_dom0_parseQvmBlock output incorrect." ; B_E }
-local i=0
-for ((i=0; i < ${blockinfo["max"]}; i++)) ; do
-	if [[ "${blockinfo["${i}_backend"]}" == "dom0" ]] && [[ "${blockinfo["${i}_device id"]}" == "$loDeviceName" ]] ; then
-		if [ -n "${blockinfo["${i}_frontend-dev"]}" ] ; then
-		       echo "/dev/${blockinfo["${i}_frontend-dev"]}"
-		       return 0
-		else
-		       B_ERR="Failed to attach."
-		       B_E
-		fi
-	fi
-done
-
-return 1
+local frontend=""
+frontend="$(b_dom0_getQvmBlockInfo "" "frontend-dev" "backend" "dom0" "device id" "$loDeviceName")" || { B_ERR="Failed to attach." ; B_E }
+echo "/dev/$frontend"
+return 0
 }
 
 #+b_dom0_attachVMDisk [source VM] [target VM] [dom0 working folder] [rw flag]
@@ -833,23 +877,10 @@ local deviceName="${sourceDevice##*/}"
 qvm-block a $addOptions "$targetVM" "${sourceVM}:${deviceName}" || { B_ERR="Failed to run qvm-block successfully." ; B_E }
 
 #retrieve info
-local blockinfo=""
-blockinfo="$(b_dom0_parseQvmBlock "blockinfo")" || { B_ERR="Failed to obtain the qvm-block ls information." ; B_E }
-eval "$blockinfo" || { B_ERR="b_dom0_parseQvmBlock output incorrect." ; B_E }
-local i=0
-for ((i=0; i < ${blockinfo["max"]}; i++)) ; do
-	if [[ "${blockinfo["${i}_backend"]}" == "$sourceVM" ]] && [[ "${blockinfo["${i}_device id"]}" == "$deviceName" ]] ; then
-		if [ -n "${blockinfo["${i}_frontend-dev"]}" ] ; then
-			echo "/dev/${blockinfo["${i}_frontend-dev"]}"
-			return 0
-		else
-			B_ERR="Failed to attach."
-			B_E
-		fi
-	fi
-done
-
-return 1
+local frontend=""
+frontend="$(b_dom0_getQvmBlockInfo "" "frontend-dev" "backend" "$sourceVM" "device id" "$deviceName")" || { B_ERR="Failed to attach." ; B_E }
+echo "/dev/$frontend"
+return 0
 }
 
 #+b_dom0_crossAttachFile [source VM] [source file] [target VM] [rw flag]
@@ -888,17 +919,7 @@ local devName="${dev##*/}"
 
 #get the backend ID
 local bid=""
-local blockinfo=""
-blockinfo="$(b_dom0_parseQvmBlock "blockinfo")" || { B_ERR="Failed to obtain the qvm-block ls information." ; B_E }
-eval "$blockinfo" || { B_ERR="b_dom0_parseQvmBlock output incorrect." ; B_E }
-local i=0
-for ((i=0; i < ${blockinfo["max"]}; i++)) ; do
-	if [[ "${blockinfo["${i}_frontend-dev"]}" == "$devName" ]] && [[ "${blockinfo["${i}_used by"]}" == "$vm" ]] ; then
-		bid="${blockinfo["${i}_backend"]}:${blockinfo["${i}_device id"]}"
-		break
-	fi
-done
-[ -z "$bid" ] && B_ERR="Failed to identify the backend ID for the device $dev in the VM $vm." && B_E
+bid="$(b_dom0_getQvmBlockInfo "" "id" "frontend-dev" "$devName" "used by" "$vm")" || { B_ERR="Failed to find the backend ID for the device $devName in the VM $vm." ; B_E }
 
 #detach & set exit code
 qvm-block d "$vm" "$bid" || { B_ERR="Failed to detach." ; B_E }
