added b_fs_isRotatingDrive, b_fs_getBlockDevice, b_fs_removeRelativelySafely

diff --git a/lib/fs b/lib/fs
--- a/lib/fs
+++ b/lib/fs
@@ -2,10 +2,10 @@
 #
 #+Collection of file and file system related functions.
 #+
-#+Copyright (C) 2018  David Hobach  LGPLv3
-#+0.3
+#+Copyright (C) 2022  David Hobach  LGPLv3
+#+0.4
 
-b_deps "wc" "findmnt" "mktemp" "mount" "head" "stat" "rm" "sync"
+b_deps "wc" "findmnt" "mktemp" "mount" "head" "stat" "rm" "sync" "cat" "lsblk"
 
 #+### Functions ###
 
@@ -237,7 +237,7 @@ echo "$ret"
 
 #+b_fs_removeWithOverwrite [file] [randomness source]
 #+Overwrite the given file with random data, then remove it. This is meant to prevent a potential reconstruction of the file after its removal.
-#+*Warning*: The reconstruction may still work on some types of file systems or physical storage systems (e.g. on flash disks).
+#+*Warning*: The reconstruction may still work on some types of file systems or physical storage systems (e.g. on flash disks/SSDs).
 #+[file]: Full path to the file to remove. Directories are currently not supported.
 #+[randomness source]: Device to use as source of random data (default: /dev/urandom).
 #+returns: Nothing. [B_E](#B_E) is called on errors.
@@ -256,6 +256,63 @@ head -c "$fsize" < "$rdev" > "$file" || { B_ERR="Failed to overwrite the file $f
 sync -d "$file" || { B_ERR="Failed to sync the file $file." ; B_E ; }
 rm -f "$file" || { B_ERR="Failed to remove the file $file." ; B_E ; }
 return 0
+}
+
+#+b_fs_isRotatingDrive [block device]
+#+Check whether the given block device is a rotating disk (non-SSD) or not.
+#+[block device]: Device name or path to check.
+#+returns: Nothing. Sets a zero exit code, if the device is a rotating one. Non-existing devices trigger [B_E](#B_E).
+#+@B_E
+function b_fs_isRotatingDrive {
+local dev="$1"
+[[ "$dev" != *"/"* ]] && dev="/dev/$dev"
+
+local ret=
+ret="$(lsblk -n -o name,rota "$dev")" || { B_ERR="The device $dev does not exist." ; B_E ; }
+[[ "$ret" == *"1" ]]
+}
+
+#+b_fs_getBlockDevice [file]
+#+Get the block device on which the given file or directory is stored.
+#+[file]: Full path to the file.
+#+returns: Full device path where the given file or directory is stored.
+#+@B_E
+function b_fs_getBlockDevice {
+local file="$1"
+findmnt -vn -o SOURCE --target "$file" || { B_ERR="Failed to get the block device for $file. Maybe it doesn't exist?" ; B_E ; }
+}
+
+#+b_fs_removeRelativelySafely [file] [randomness source]
+#+A best-effort implementation that attempts to remove files from the file system in a non-reconstructible way.
+#+Contrary to [b_fs_removeWithOverwrite](#b_fs_removeWithOverwrite) it'll attempt to achieve similar results on SSDs.
+#+**May require root privileges.**
+#+*Warning*: The reconstruction may still work depending on your hardware.
+#+[file]: Full path to the file to remove. Directories are currently not supported.
+#+[randomness source]: Device to use as source of random data (default: /dev/urandom).
+#+returns: Nothing. [B_E](#B_E) is called on errors.
+#+@B_E
+function b_fs_removeRelativelySafely {
+local file="$1"
+local rdev="${2:-/dev/urandom}"
+
+[ -c "$rdev" ] || { B_ERR="Nonexisting randomness source: $rdev" ; B_E ; }
+
+local fdev=
+fdev="$(b_fs_getBlockDevice "$file")" || { B_ERR="Failed to get the block device for $file. Maybe it doesn't exist?" ; B_E ; }
+
+if b_fs_isRotatingDrive "$fdev" ; then
+	b_fs_removeWithOverwrite "$file" "$rdev" || B_E
+else
+	#fstrim usually needs root privileges, so we check for it here
+	b_deps "fstrim"
+	local pmnt=
+	pmnt="$(findmnt -n -o TARGET --target "$file")" || { B_ERR="Failed to find the parent mount point for $file." ; B_E ; }
+	#SSD:
+	#no point in overwriting as that will just write to other blocks (SSD "wear leveling")
+	#--> just remove and trim afterwards and hope that the device trims in a way that overwrites old data
+	rm -f "$file" || { B_ERR="Failed to remove the file $file." ; B_E ; }
+	fstrim "$pmnt" || { B_ERR="Failed to fstrim the mount point $pmnt. Reconstructing $file is very likely possible." ; B_E ; }
+fi
 }
 
 #implementation of b_fs_enumerate
