added by_types_str & b_types_int

diff --git a/lib/types b/lib/types
--- a/lib/types
+++ b/lib/types
@@ -2,8 +2,8 @@
 #
 #+Functions for data type checks and conversions.
 #+
-#+Copyright (C) 2021  David Hobach  LGPLv3
-#+0.5
+#+Copyright (C) 2022  David Hobach  LGPLv3
+#+0.6
 
 b_deps "python3"
 
@@ -19,6 +19,19 @@ declare -gA B_TYPES_ENCODINGS=(
 	["32-bit-bigendian"]="unsupported"
 	["32-bit-littleendian"]="unsupported"
 	)
+
+#+B_TYPES_ENCODING
+#+String encoding parameter for [b_types_str](#b_types_str) and [b_types_parseString)(#b_types_parseString). Default: ascii
+#+`ascii` makes sense in 99% of all cases as scripts should use ASCII only anyway (when no user-interaction is involved) in order to remain portable. Keep in mind that bash also needs to support the target encoding in order to support further processing. Currently available encodings: <https://docs.python.org/3.7/library/codecs.html#standard-encodings>
+B_TYPES_ENCODING="ascii"
+
+#+B_TYPES_MAX_BYTES
+#+Parameter for [b_types_str](#b_types_str) and [b_types_parseString)(#b_types_parseString) to specify the maximum number of bytes to read per line (default: -1/infinite). Ignore additional bytes. Useful to avoid memory DoS for untrusted input.
+B_TYPES_MAX_BYTES=-1
+
+#+B_TYPES_CHECK_NON_BINARY
+#+Whether or not [b_types_int](#b_types_int) should also ensure that the command output is non-binary (default: 0/true).
+B_TYPES_CHECK_NON_BINARY=0
 
 #+### Functions ###
 
@@ -41,13 +54,13 @@ declare -gA B_TYPES_ENCODINGS=(
 #+ [ $? -eq 0 ] && echo "Found the following string: $str"
 #+```
 #+
-#+[encoding]: The encoding of the string lying in stdin. Defaults to `ascii`, which makes sense in 99% of all cases as scripts should use ASCII only anyway (when no user-interaction is involved) in order to remain portable. Keep in mind that bash also needs to support the target encoding in order to support further processing. Currently available encodings: <https://docs.python.org/3.7/library/codecs.html#standard-encodings>
-#+[max bytes]: Maximum number of bytes to read per line (default: -1/infinite). Ignore additional bytes. Useful to avoid memory DoS for untrusted input.
+#+[encoding]: The encoding of the string lying in stdin. Default: [B_TYPES_ENCODING](#B_TYPES_ENCODING)/ascii
+#+[max bytes]: Maximum number of bytes to read per line. Additional bytes are ignored. Default: [B_TYPES_MAX_BYTES](#B_TYPES_MAX_BYTES)/-1/infinite
 #+returns: The data as String, if the input data was found to be a String. If no String was found to be lying in stdin, the output is an undefined string and a non-zero exit code is set. [B_E](#B_E) is only called on exceptional errors.
 #+@B_E
 function b_types_parseString {
-local encoding="${1:-"ascii"}"
-local maxBytes="${2:-"-1"}"
+local encoding="${1:-"$B_TYPES_ENCODING"}"
+local maxBytes="${2:-"$B_TYPES_MAX_BYTES"}"
 
 if [ -z "$encoding" ] || [[ "$encoding" == "unsupported" ]] ; then
 	B_ERR="This encoding is no longer supported. Please migrate to the new syntax."
@@ -64,22 +77,89 @@ ret=$?
 return $ret
 }
 
+#+b_types_str [cmd] [cmd arg 1] ... [cmd arg n]
+#+Execute the given command and ensure that its output / stdout is a string.
+#+Use [B_TYPES_ENCODING](#B_TYPES_ENCODING) to specify the encoding (default: ascii) and [B_TYPES_MAX_BYTES](#B_TYPES_MAX_BYTES) (default: -1/infinite) to specify the maximum number of bytes to read.
+#+[cmd]: Command to execute. Stdout is checked to be a string, stderr is passed through.
+#+[cmd arg i]: Arguments to pass to \[cmd\].
+#+returns: Stdout of \[cmd\], if it is a string and an undefined string otherwise. The exit code is that of the executed command. [B_E](#B_E) is called if the output is _not_ a string.
+#+@B_E
+function b_types_str {
+[ -z "$1" ] && B_ERR="No command specified." && B_E
+
+local ret=
+"$@" | b_types_parseString
+ret=(${PIPESTATUS[@]})
+[ ${ret[1]} -ne 0 ] && B_ERR="The command \"$1\" did not return a string." && B_E
+return ${ret[0]}
+}
+
+#blib_types_printInteger [str]
+#Print the given string, if it is an integer.
+#returns: Sets a zero exit code, if it's an integer.
+function blib_types_printInteger {
+local str="$1"
+local re='^[\+-]?[0-9]+$'
+[[ "$str" =~ $re ]] || return 1
+printf '%d\n' "$str"
+}
+
+#blib_types_parseInteger
+#Read stdin until its end and print it, if it is an integer.
+#returns: Sets a zero exit code, if it's an integer.
+function blib_types_parseInteger {
+local str line
+local cnt=0
+IFS= read -r str
+
+#make sure there's nothing left in stdin
+while IFS= read -r line ; do
+	cnt=$(($cnt +1))
+done
+[ $cnt -eq 0 ] || return 1
+
+blib_types_printInteger "$str"
+}
+
 #+b_types_isInteger [string]
 #+Check whether the given String is an integer (positive or negative) or not.
-#+[string]: The string to check. If it may be binary data, please make sure to pass it through [b_types_parseString](#b_types_parseString) first.
+#+[string]: The string to check. If it may be binary data, please make sure to pass it through [b_types_parseString](#b_types_parseString) or [b_types_str](#b_types_str) first.
 #+returns: Nothing, but sets a zero exit code if and only if the given string represents an integer.
 function b_types_isInteger {
-printf "%d" "$1" &> /dev/null
+blib_types_printInteger "$@" &> /dev/null
 }
 
 #+b_types_assertInteger [string] [error msg]
 #+Check whether the given String is an integer (positive or negative) and if not, error out.
-#+[string]: The string to check. If it may be binary data, please make sure to pass it through [b_types_parseString](#b_types_parseString) first.
+#+[string]: The string to check. If it may be binary data, please make sure to pass it through [b_types_parseString](#b_types_parseString) or [b_types_str](#b_types_str) first.
 #+[error msg]: Error message to use, if the check fails (optional).
 #+returns: Nothing. If it's no integer, [B_E](#B_E) is called.
 #+@B_E
 function b_types_assertInteger {
 b_types_isInteger "$1" || { B_ERR="${2:-"No integer: $1"}" ; B_E }
+}
+
+#+b_types_int [cmd] [cmd arg 1] ... [cmd arg n]
+#+Execute the given command and ensure that its output / stdout is an integer (positive or negative).
+#+[B_TYPES_CHECK_NON_BINARY](#B_TYPES_CHECK_NON_BINARY) can be used to enable/disable additional non-binary checking (default: 0/enabled).
+#+[cmd]: Command to execute. Stdout is checked to be an integer, stderr is passed through.
+#+[cmd arg i]: Arguments to pass to \[cmd\].
+#+returns: Stdout of \[cmd\], if it is an integer and an undefined string otherwise. The exit code is that of the executed command. [B_E](#B_E) is called if the output is _not_ an integer.
+#+@B_E
+function b_types_int {
+[ -z "$1" ] && B_ERR="No command specified." && B_E
+
+local ret=
+if [ $B_TYPES_CHECK_NON_BINARY -eq 0 ] ; then
+	b_types_str "$@" | blib_types_parseInteger 2> /dev/null
+else
+	#unsure whether it is a good idea to do this with untrusted binary data...
+	#--> default to the safe variant
+	"$@" | blib_types_parseInteger 2> /dev/null
+fi
+ret=(${PIPESTATUS[@]})
+[ ${ret[1]} -ne 0 ] && B_ERR="The command \"$1\" did not return an integer." && B_E
+return ${ret[0]}
 }
 
 #+b_types_looksLikeArray [string]
